version: "3"

services:
  app:
    image: nirodg/invoice-ninja:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ninja/storage:/var/www/app/storage:rw
      - ./ninja/logo:/var/www/app/public/logo:rw
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "ninja"
      MYSQL_DATABASE: "ninja"
      MYSQL_USER: "ninja"
      MYSQL_PASSWORD: "ninja"
